application: where-do-you-go
version: 10-0
runtime: python
api_version: 1

handlers:

- url: /favicon.ico|/public/favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /delete_data/mapimage
  script: scripts/delete_data.py
  login: required

- url: /delete_data/user|/delete_data/all
  script: scripts/delete_data.py
  login: required

- url: /update_user_color/.*
  script: scripts/update_user_color.py
  login: required

- url: /update_user_level/.*
  script: scripts/update_user_level.py
  login: required

- url: /generate_static_map/.*
  script: scripts/update_user_maps.py
  login: required

- url: /draw_static_tile/.*
  script: scripts/update_user_maps.py
  login: admin

- url: /fetch_foursquare_data/next_for_user/.*
  script: scripts/fetch_foursquare_data.py
  login: admin

- url: /fetch_foursquare_data/clear_old_uservenues
  script: scripts/fetch_foursquare_data.py
  login: admin

- url: /static
  static_dir: static

- url: .*
  script: handlers.py