application: checkalor
version: 0-1
runtime: python
api_version: 1

handlers:

# - url: /remote_api
#   script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
#   login: admin
    
- url: /public/favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /delete_data/all
  script: scripts/delete_data.py
  login: admin

- url: /delete_data/mapimage
  script: scripts/delete_data.py
  login: required

- url: /delete_data/user
  script: scripts/delete_data.py
  login: required

- url: /update_user_color/.*
  script: scripts/update_user_color.py
  login: required

- url: /update_user_level/.*
  script: scripts/update_user_level.py
  login: required

- url: /generate_static_map/one
  script: scripts/update_user_maps.py
  login: admin

- url: /generate_static_map/.*
  script: scripts/update_user_maps.py
  login: required


- url: /fetch_foursquare_data/update_users_batch
  script: scripts/fetch_foursquare_data.py
  login: admin

- url: /fetch_foursquare_data/all_for_user/.*
  script: scripts/fetch_foursquare_data.py
  login: admin

- url: /clear_authtokens
  script: scripts/clear_authtokens.py
  login: admin

- url: /clear_parentless_uservenues
  script: scripts/clear_parentless_uservenues.py
  login: admin

- url: /view_venues
  script: handlers.py
  login: admin

- url: /static
  static_dir: static

- url: .*
  script: handlers.py