application: where-do-you-go-hrd
version: 13-1
runtime: python27
threadsafe: false
api_version: 1

handlers:

- url: /favicon.ico|/public/favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /delete_data/user|/delete_data/mapimage
  script: scripts/delete_data.py
  login: required

- url: /delete_data/all
  script: scripts/delete_data.py
  login: admin

- url: /static
  static_dir: static

- url: .*
  script: handlers.py
